#!/usr/bin/env bash
#
# Regenerate the GitHub wiki from the documentation in this repository.
#
# The wiki is the public source of truth, but it lives in a second git repository that nothing
# builds or tests. Left to hand-editing it drifts: the last hand-written version sat on 2.0.0 while
# the mod shipped 2.4.0, and nobody noticed because nothing could notice. So the wiki is generated,
# and the documents in docs/ stay the thing anyone edits.
#
# Usage:
#   tools/sync-wiki.sh [path-to-wiki-clone]      # writes the pages
#   tools/sync-wiki.sh --check [path]            # exits non-zero if the wiki is out of date
#
# The wiki clone is a normal git repository:
#   git clone https://github.com/DrimoZ/PunchThemAll.wiki.git
# Review the diff and push it yourself. This script never pushes.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK_ONLY=false

if [ "${1:-}" = "--check" ]; then
    CHECK_ONLY=true
    shift
fi

WIKI="${1:-$REPO_ROOT/../PunchThemAll.wiki}"

if [ ! -d "$WIKI" ]; then
    echo "No wiki clone at $WIKI" >&2
    echo "Clone it first: git clone https://github.com/DrimoZ/PunchThemAll.wiki.git" >&2
    exit 2
fi

BLOB="https://github.com/DrimoZ/PunchThemAll/blob/master"

# docs/<source>.md -> <Wiki-Page>.md
PAGES="
getting-started:Getting-Started
cookbook:Cookbook
capabilities:Capabilities
interaction-format:Interaction-Format
configuration:Configuration
interactions:Datapacks-and-Viewers
troubleshooting:Troubleshooting
"

# Rewrite the links a page uses so they point at wiki pages rather than at files on disk.
# Anything with no wiki equivalent — the schema, the backlog, the example files themselves — points
# back into the repository instead, so no link is left dangling.
rewrite_links() {
    sed -E \
        -e 's#\]\((\.\./)*(docs/)?getting-started\.md#](Getting-Started#g' \
        -e 's#\]\((\.\./)*(docs/)?cookbook\.md#](Cookbook#g' \
        -e 's#\]\((\.\./)*(docs/)?capabilities\.md#](Capabilities#g' \
        -e 's#\]\((\.\./)*(docs/)?interaction-format\.md#](Interaction-Format#g' \
        -e 's#\]\((\.\./)*(docs/)?configuration\.md#](Configuration#g' \
        -e 's#\]\((\.\./)*(docs/)?interactions\.md#](Datapacks-and-Viewers#g' \
        -e 's#\]\((\.\./)*(docs/)?troubleshooting\.md#](Troubleshooting#g' \
        -e 's#\]\(docs/porting/([^)]*)\)#]('"$BLOB"'/docs/porting/\1)#g' \
        -e 's#\]\(\.\./examples/punchthemall-examples/README\.md\)#](Examples)#g' \
        -e 's#\]\(\.\./examples/punchthemall-examples\)#](Examples)#g' \
        -e 's#\]\(\.\./\.\./docs/cookbook\.md\)#](Cookbook)#g' \
        -e 's#\]\(\.\./\.\./docs/backlog\.md\)#]('"$BLOB"'/docs/backlog.md)#g' \
        -e 's#\]\(\.\./CHANGELOG\.md\)#](Changelog)#g' \
        -e 's#\]\(interaction\.schema\.json\)#]('"$BLOB"'/docs/interaction.schema.json)#g' \
        -e 's#\]\(backlog\.md#]('"$BLOB"'/docs/backlog.md#g' \
        -e 's#\]\(\.\./examples/dev-probe-pack\)#]('"$BLOB"'/examples/dev-probe-pack)#g'
}

banner() {
    echo "<!--"
    echo "  Generated from $1 by tools/sync-wiki.sh. Edit that file, not this page:"
    echo "  a hand edit here is lost the next time anyone runs the script."
    echo "-->"
    echo
}

OUT_DIR="$(mktemp -d)"
trap 'rm -rf "$OUT_DIR"' EXIT

for entry in $PAGES; do
    src="${entry%%:*}"
    page="${entry##*:}"
    { banner "docs/$src.md"; rewrite_links < "$REPO_ROOT/docs/$src.md"; } > "$OUT_DIR/$page.md"
done

{ banner "examples/punchthemall-examples/README.md"; rewrite_links < "$REPO_ROOT/examples/punchthemall-examples/README.md"; } > "$OUT_DIR/Examples.md"
{ banner "CHANGELOG.md"; rewrite_links < "$REPO_ROOT/CHANGELOG.md"; } > "$OUT_DIR/Changelog.md"

MOD_VERSION="$(grep -E '^mod_version=' "$REPO_ROOT/gradle.properties" | cut -d= -f2)"
MC_VERSION="$(grep -E '^minecraft_version=' "$REPO_ROOT/gradle.properties" | cut -d= -f2)"
EXAMPLE_COUNT="$(find "$REPO_ROOT/examples/punchthemall-examples" -name '*.json' -path '*interaction*' | wc -l | tr -d ' ')"

cat > "$OUT_DIR/Home.md" <<EOF
<!--
  Generated by tools/sync-wiki.sh from the repository documentation.
  Edit docs/ in the main repository, not this page.
-->

# PunchThemAll

**Turn any click into a recipe.** Define what happens when a player left- or right-clicks (sneaking
or not) on a block, a fluid, or the air — optionally holding a particular item. Plain JSON in a
datapack. No Java, no scripting.

Currently **Minecraft $MC_VERSION**, mod version **$MOD_VERSION**.

## Start here

| | |
| --- | --- |
| **New to the mod** | [Getting Started](Getting-Started) — builds an interaction from scratch, one feature at a time |
| **Building something specific** | [Cookbook](Cookbook) — whole working recipes by goal, each combining several fields |
| **Wondering if something is possible** | [Capabilities](Capabilities) — what it can do, what it cannot, and the traps in between |
| **Looking up a field** | [Interaction Format](Interaction-Format) — every field of \`schema_version: 2\` |
| **Something is not working** | [Troubleshooting](Troubleshooting) — in the order that finds it fastest |

## Reference

- [Configuration](Configuration) — every \`pta-common.toml\` key, with presets
- [Datapacks and Viewers](Datapacks-and-Viewers) — loading, ids, multiplayer sync, JEI and EMI
- [Examples](Examples) — $EXAMPLE_COUNT runnable interactions, catalogued with what to click
- [Changelog](Changelog)
- [Community](Community) — Discord, issues, CurseForge

## What an interaction looks like

\`\`\`json
{
  "schema_version": 2,
  "type": "shift_left_click",
  "hand": { "hand": "main", "match": "#minecraft:shovels", "consume": { "mode": "durability" } },
  "target": { "kind": "block", "match": "minecraft:gravel" },
  "transformation": { "chance": 0.7, "into": { "kind": "block", "id": "minecraft:sand" } },
  "rewards": { "weighted": [
    { "match": "minecraft:flint", "weight": 25 },
    { "match": "minecraft:air",   "weight": 75 }
  ] }
}
\`\`\`

Sneak-left-click gravel with a shovel: it sometimes gives flint, and usually turns to sand. Drop the
file in a datapack, run \`/reload\`, and it shows up in JEI.

---

> This wiki is generated from the documentation in the
> [main repository]($BLOB/docs). Corrections belong there — a change made here is
> overwritten the next time the wiki is regenerated.
EOF

cat > "$OUT_DIR/_Sidebar.md" <<EOF
* [Home](Home)
* [Getting Started](Getting-Started)
  * [Your first interaction](Getting-Started#2-your-first-interaction)
  * [Drops](Getting-Started#4-drops)
  * [Transforming the block](Getting-Started#6-transforming-the-block)
  * [Conditions](Getting-Started#9-conditions)
* [Cookbook](Cookbook)
  * [Gathering](Cookbook#gathering)
  * [Tools that reach](Cookbook#tools-that-reach)
  * [Building](Cookbook#building-and-terraforming)
  * [Multi-block setups](Cookbook#multi-block-setups)
* [Capabilities](Capabilities)
  * [What it can do](Capabilities#what-it-can-do)
  * [What it cannot do](Capabilities#what-it-cannot-do)
  * [Traps](Capabilities#things-that-look-possible-and-are-not)
  * [Limits](Capabilities#limits-with-numbers-on-them)
* [Interaction Format](Interaction-Format)
  * [Full shape](Interaction-Format#full-shape-all-sections-optional-except-type)
  * [Transformations](Interaction-Format#transformations-what-and-where)
  * [Regions](Interaction-Format#acting-on-a-whole-region)
  * [Neighbours](Interaction-Format#requiring-a-block-nearby)
  * [NBT predicates](Interaction-Format#typed-nbt-predicates-nbt_predicates)
* [Configuration](Configuration)
* [Datapacks and Viewers](Datapacks-and-Viewers)
* [Examples](Examples)
* [Troubleshooting](Troubleshooting)
* [Changelog](Changelog)
* [Community](Community)
EOF

cat > "$OUT_DIR/_Footer.md" <<EOF
<div align="center">

[Home](Home) | [Getting Started](Getting-Started) | [Cookbook](Cookbook) | [Capabilities](Capabilities) | [Interaction Format](Interaction-Format) | [Troubleshooting](Troubleshooting) | [Community](Community)
</div>

---

**PunchThemAll $MOD_VERSION** for Minecraft $MC_VERSION. Code under the
[MIT Licence]($BLOB/LICENSE); artwork under [LICENSE-ASSETS]($BLOB/LICENSE-ASSETS).
Use it in any modpack, public or private — no permission needed, credit never required.

This wiki is generated from [docs/]($BLOB/docs); edit there.
EOF

# Community is the one page with no counterpart in the repository, so it is left alone.
CHANGED=0
for generated in "$OUT_DIR"/*.md; do
    name="$(basename "$generated")"
    if ! cmp -s "$generated" "$WIKI/$name"; then
        CHANGED=1
        if [ "$CHECK_ONLY" = true ]; then
            echo "out of date: $name"
        else
            cp "$generated" "$WIKI/$name"
            echo "updated: $name"
        fi
    fi
done

if [ "$CHECK_ONLY" = true ]; then
    if [ "$CHANGED" -eq 1 ]; then
        echo "The wiki is behind the documentation. Run tools/sync-wiki.sh to regenerate it." >&2
        exit 1
    fi
    echo "The wiki matches the documentation."
    exit 0
fi

if [ "$CHANGED" -eq 0 ]; then
    echo "Already up to date."
else
    echo
    echo "Review and push:"
    echo "  git -C \"$WIKI\" diff"
    echo "  git -C \"$WIKI\" add -A && git -C \"$WIKI\" commit -m \"Sync wiki with docs\" && git -C \"$WIKI\" push"
fi
